# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         rrdpoller
version:      1.0.1
version_from: rrdpoller
installdirs:  site
requires:
    Error:                         0.15
    RRDs:                          1.000481

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
